
document.write("<div id=\"navegador\">")
document.write("<nav>")
document.write("<center>")
document.write("<ul>")
document.write("<li> Players <\/li>")
document.write("<li><a href=»#accommodations>Accommodations<\/a><\/li>")
document.write("<li><a href=»#hosts»>Hosts<\/a><\/li>")
document.write("<li><a href=»#sponsors»>Sponsors<\/a><\/li>")
document.write("<li><a href=»#games»>Games<\/a><\/li>")
document.write("<li><a href=»#licenses»>Licenses<\/a><\/li>")
document.write("<li><a href=»#championships»>Championships<\/a><\/li>")
document.write("<li><a href=»#sponsors»>Sponsors<\/a><\/li>")
document.write("<\/ul>")
document.write("<\/center>")
document.write("<\/nav>")
document.write("<\/div>")
