version: '3.8'
services:

  postgres-db:
    build: database
    hostname: database
    container_name: database
    environment:
      POSTGRES_DB: wehka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lop34sw@D
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


