version: '3.8'
services:

  access-api:
    build: database_access_api
    hostname: database_access_api
    container_name: database_access_api
    volumes:
      - ./access-api/:/app # Necesito buscar esto para saber como hacerlo.
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db

  postgres-db:
    build: database
    hostname: database
    container_name: database
    environment:
      POSTGRES_DB: wehka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lop34sw@D
    volumes:
      # - ./database/:/app # No lo tengo y parece que funciona perfectamente.
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always # Para mantener el sistema activo. Creo que no es necesario


